name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs at midnight every day
  workflow_dispatch:     # allows manual trigger from GitHub UI

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: het875
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push generated SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
